Alexis/js
acmucsd/hack-website pull request #10
Opened 2023-08-17 01:47 UTC by AVERGNET

Has both the JS page and CSS page

2023-08-18 06:08 UTC, khushijpatel requested changes
There are a few typos in the code examples. Other than that looks good

2023-08-18 06:08 UTC, khushijpatel commented on pages/hack-school/js.mdx
> +constant greeting = "hey";
typo, 'const'

2023-08-18 06:08 UTC, khushijpatel commented on pages/hack-school/js.mdx
> +console.log(greety); // hey
typo, 'greeter'

2023-08-18 06:08 UTC, khushijpatel commented on pages/hack-school/js.mdx
> +const myNmae = organization.name;
typo, assuming you meant 'myName' since in the next line you are log 'myName'

2023-08-18 06:08 UTC, khushijpatel commented on pages/hack-school/js.mdx
> +const myNmae = organization[age];
typo, 'myName'

2023-08-20 17:44 UTC, nik-dange commented on pages/hack-school/css.mdx
> +# Week 1 CSS
Let's have the format as `Week 1: CSS`, and we can use this across the textbook.

2023-08-20 17:50 UTC, nik-dange requested changes

2023-08-20 17:50 UTC, nik-dange commented on pages/hack-school/css.mdx
> +## What is CSS
Add a question mark at the end

2023-08-20 17:50 UTC, nik-dange commented on pages/hack-school/css.mdx
> +## Applying CSS to HTML components
As a general note for keeping things consistent, let's capitalize all words in titles, except for minor words like `to` : `Applying CSS to HTML Components`

2023-08-20 17:50 UTC, nik-dange commented on pages/hack-school/css.mdx
> +## Applying CSS to HTML components
Let's do this for anything that's a title or heading

2023-08-20 17:50 UTC, nik-dange commented on pages/hack-school/js.mdx
> +## Introduction to JavaScript
Let's call this `What is JavaScript?` for the sake of starting all pages in the same way

2023-08-20 17:50 UTC, nik-dange commented on pages/hack-school/js.mdx
> +|redecalred |   ❌      |   ❌     |   ✅      |
Typo, should be `redeclared`

2023-08-21 04:50 UTC, nik-dange approved these changes
lgtm 🚀

2023-08-21 04:55 UTC, khushijpatel approved these changes
Looks good! Great work!!

2023-08-21 04:57 UTC, merged