Alexis/git git hub
acmucsd/hack-website pull request #15
Opened 2023-08-22 03:17 UTC by AVERGNET

Git and GitHub page

2023-08-22 21:44 UTC, angela139 commented on pages/hack-school/git-github.mdx
> +### Git Instalation (Windows)
Installation

2023-08-22 21:46 UTC, angela139 commented on pages/hack-school/git-github.mdx
> +### Git Instalation (Windows)
Should be Git Installation

2023-08-22 21:47 UTC, angela139 commented on pages/hack-school/git-github.mdx
> +7. Veriffy that it was correctly installed by opening any command prompt and typing:
Typo: Verify

2023-08-22 21:47 UTC, angela139 commented on pages/hack-school/git-github.mdx
> +If everythting worked correctly it should print something like this:
Typo: everything

2023-08-22 22:14 UTC, angela139 requested changes
Overall, the content is really good and concise! I found some spelling typos and made some suggestions.

2023-08-22 22:14 UTC, angela139 commented on pages/hack-school/git-github.mdx
> +### Git Instalation (Windows)
Also, I know Git is already installed on most Macs, but if there are git installation instructions for Windows, I think you can add a small section for Mac: 

### Git Installation (Mac)
Most versions of MacOS will already have Git installed, and you can activate it through the terminal with `git version`. However, if you don't have Git installed, you can install the latest version of Git through this [link](https://git-scm.com/download/mac).

2023-08-23 02:24 UTC, nik-dange commented
Content looks good! Can we add some pictures in there? In particular, I think a picture showing the environment between your local repo, staging area, remote repo, etc. would be helpful to visualize how changes are made. Something like this
![image](https://github.com/acmucsd/hack-website/assets/16010723/30287345-addc-4ea6-bc09-86cfa0007703) might be helpful, I know there's also a good example on the git website itself.

2023-08-23 03:13 UTC, khushijpatel reviewed
Great content, love the simplicity & detail with the steps! Left a couple suggestions

2023-08-23 03:13 UTC, khushijpatel commented on pages/hack-school/git-github.mdx
> +
maybe we can add a little snippet on cloning & forking?

2023-08-23 03:13 UTC, khushijpatel commented on pages/hack-school/git-github.mdx
> +
maybe add a section on cloning, forking & PR?

2023-08-28 07:50 UTC, AVERGNET commented on pages/hack-school/git-github.mdx
> +
I will put all cloning, forking and pr in github instead of under git

2023-08-28 08:16 UTC, nishantbalaji requested changes
overall, looks great! i left some comments where that i think things could be a bit more clear or restructured

2023-08-28 08:16 UTC, nishantbalaji commented on pages/hack-school/git-github.mdx
> +1. Go to https://github.com/
just a pet peeve of mine, but i don't like the `https://` in urls. lets remove the it from this url and make it `[github.com](https://github.com)`

2023-08-28 08:20 UTC, AVERGNET commented on pages/hack-school/git-github.mdx
> +### Git Instalation (Windows)
I agree this makes more sense

2023-08-28 08:22 UTC, AVERGNET commented on pages/hack-school/git-github.mdx
> +### Git Instalation (Windows)
oh my bad, missed that, thank you

2023-08-28 08:34 UTC, nishantbalaji commented
Let's also change the PR name here to `Git and Github`

2023-08-28 08:58 UTC, nishantbalaji commented
I'll review fully in the morning but irt pr name: remove the Alexis/ from it

2023-08-28 20:44 UTC, nishantbalaji reviewed
Looking better! a note to add some more images so the reader can get more detailed context!

2023-08-28 20:44 UTC, nishantbalaji commented on pages/hack-school/git-github.mdx
> +git --version
`git version` here as well

2023-08-28 20:44 UTC, nishantbalaji commented on pages/hack-school/git-github.mdx
> +Branching allows developers to create separate lines of development within a repository. The main branch (often 'master' or 'main') serves as the foundation. Feature branches are created for specific
maybe a little example here how branches help a work flow? smth like i.e. you make x change on this branch and someone makes y change on another branch and how this can happen concurrently without clashing?

2023-08-28 20:44 UTC, nishantbalaji commented on pages/hack-school/git-github.mdx
> +GitHub is a web-based platform built on top of Git. It provides an interface for hosting and collaborating on Git repositories. GitHub offers additional features, such as issue tracking, project mana
Link Github -> `[Github](https://github.com)`

2023-08-28 20:44 UTC, nishantbalaji commented on pages/hack-school/git-github.mdx
> +Pull requests are a core feature of GitHub's collaborative workflow. They allow developers to propose changes and improvements to a repository. After creating a pull request, other team members revie
Talk about Merge vs Squash and merge vs Rebase and merge etc

2023-08-28 20:44 UTC, nishantbalaji commented on pages/hack-school/git-github.mdx
> +Example Workflow YAML:
explain what this workflow does

2023-08-28 20:44 UTC, nishantbalaji commented on pages/hack-school/git-github.mdx
> +![git/github flow](pages/hack-school/github_flow.png)
explain image

2023-08-28 20:44 UTC, nishantbalaji commented on pages/hack-school/git-github.mdx
> +    * Pull any existing content from the 'main' branch of the remote repository into your local repository. This ensures that your local repository is synced.
```suggestion
    * Pull any existing content from the 'main' branch of the remote repository into your local repository. This ensures that your local repository is synced with the version on Github.
```

2023-08-28 20:44 UTC, nishantbalaji commented on pages/hack-school/git-github.mdx
> +
nit: remove line

2023-08-28 20:44 UTC, nishantbalaji commented on pages/hack-school/git-github.mdx
> +**Using GitHub:**
images to show

2023-08-28 20:44 UTC, nishantbalaji commented on pages/hack-school/git-github.mdx
> +**Using GitHub:**
images

2023-08-28 20:44 UTC, nishantbalaji commented on pages/hack-school/git-github.mdx
> +**Using GitHub:**
images

2023-08-28 20:44 UTC, nishantbalaji commented on pages/hack-school/git-github.mdx
> +**Using GitHub:**
images

2023-08-28 20:44 UTC, nishantbalaji commented on pages/hack-school/github_flow.png
nit: make the background on this picture transparent and make the "Local" and "Remote" text in a color that shows in both dark and light modes, like orange

2023-09-07 05:44 UTC, nishantbalaji approved these changes
nice work! lgtm 🚢

2023-09-08 00:36 UTC, angela139 approved these changes

2023-09-08 00:37 UTC, angela139 reviewed
Everything looks good to me!

2023-09-08 01:21 UTC, merged