Charvi/html
acmucsd/hack-website pull request #17
Opened 2023-08-23 20:41 UTC by charvishukla

This one should have everything (or i'm just crazy). Again, if you have any inputs on topics to add, remove or reorder, let me know.

2023-08-27 22:05 UTC, nik-dange requested changes
Great work! This chapter looks good to me, I made a few small suggestions for typos and nits. Let me know if you have any questions.

2023-08-27 22:05 UTC, nik-dange commented on pages/hack-school/html.mdx
> +So in this casem when you click the button, the `doSomethingFunction()` gets triggered. This could be implemented in
Typo for "case"

2023-08-27 22:05 UTC, nik-dange commented on pages/hack-school/html.mdx
> +**HTML** or **Hyper Text Markup Language**, is the standard "language" used for creating websites (note: it
This is definitely a longer chapter (for good reason), so let's add a sentence disclaimer about how it's a long section and people shouldn't worry if it looks daunting

2023-08-27 22:05 UTC, nik-dange commented on pages/hack-school/html.mdx
> +This is a very important section to urge people to stop using screenshots and images to display equations on
Let's add a sentence here about how this is a fun little bonus

2023-08-27 22:05 UTC, nik-dange commented on pages/hack-school/html.mdx
> +ever need. The `<body> <\body>` tags contain all the rest of our content! :)
Let's add a quick sentence concluding this section and encouraging people to read on to the CSS section for styling pages.

2023-08-27 22:05 UTC, nik-dange commented on pages/hack-school/_meta.json
>    "css": "Week 1: HTML & CSS",
Let's rename this to Week 1: CSS, and reorder it so it goes:
Week 1: HTML
Week 1: CSS
Week 2: JavaScript

2023-08-28 08:32 UTC, nishantbalaji requested changes
great work! i love the explanations and the writing, its very descriptive :DD my main nit is that you could have some more pictures here and there, maybe this is a great place to utilize the [library i linked in discord](https://snappify.com/).

2023-08-28 08:32 UTC, nishantbalaji commented on yarn.lock
why are we changing to a npm registry? we should stay with yarn -- could you revert your changes here unless you added a new package (in which case just add the new package)

2023-08-28 08:32 UTC, nishantbalaji commented on package-lock.json
this follows the change in `yarn.lock` revert unless u added a new package

2023-08-28 08:32 UTC, nishantbalaji commented on pages/hack-school/_meta.json
>    "css": "Week 1: HTML & CSS",
lol javascript sandwich rn

2023-08-28 08:32 UTC, nishantbalaji commented on pages/hack-school/html.mdx
> +| Subscript       | `<sub>...</sub>`                           |
nit: you do the table `code | description` in one and `description | code` in the other -- lets be consistent ? idk if this makes sense tho it might be better like u did it for readability

2023-08-28 08:34 UTC, nishantbalaji commented
Let's change the PR name here to `HTML` or `HTML and CSS` if you do both in this PR

2023-08-28 21:55 UTC, angela139 reviewed
I think the content was really good! I left some comments about typos and places you can try to add more images/visualization. For the code blocks, I also saw that you can't copy them but you can copy them for the CSS/Javascript pages that Alexis worked on. You should probably make them all copy-able.

2023-08-28 21:55 UTC, angela139 commented on pages/hack-school/html.mdx
> +    <p> Welcome to Hack Schooll 2023 </p>
Typo: School

2023-08-28 21:55 UTC, angela139 commented on pages/hack-school/html.mdx
> +### Lists
Should probably have in-line HTML visual so people reading the textbook can differentiate unordered list and ordered list more easily. Maybe try using the tabs feature on nextra to show the code on one tab and then output on the other

2023-08-28 21:55 UTC, angela139 commented on pages/hack-school/html.mdx
> +a sentence appear brown, I can do somthing like this:
Typo: something

2023-08-28 21:55 UTC, angela139 commented on pages/hack-school/html.mdx
> +<select name="cats" id="cats">
Prob add an either in-line HTML or image/gif for this

2023-09-03 20:32 UTC, charvishukla commented on yarn.lock
wait i have yarn issues on my laptop and have to use npm :( I'll try to change tho

2023-09-03 20:36 UTC, charvishukla commented on pages/hack-school/html.mdx
> +<select name="cats" id="cats">
omg cat image time gehgeheheh

2023-09-14 22:50 UTC, nik-dange approved these changes
lgtm

2023-09-15 00:02 UTC, nishantbalaji approved these changes
🍰

2023-09-15 20:03 UTC, merged