README update for repository
acmucsd/hack-website pull request #22
Opened 2023-09-05 18:07 UTC by nik-dange

- Updated README to reflect the repository better. Let me know if anything should be added/removed

2023-09-05 18:17 UTC, nik-dange commented
Also added some miscellaneous housekeeping edits to close some issues

2023-09-07 05:53 UTC, nishantbalaji requested changes
looks good overall but i have nits 🍡

2023-09-07 05:53 UTC, nishantbalaji commented on README.md
> +# hack-website
capitalize, name it `ACM Hack Website`

2023-09-07 05:53 UTC, nishantbalaji commented on README.md
>  [**Live Demo (https://hack-website-acmucsd.vercel.app/)**](https://hack-website-acmucsd.vercel.app/)
```suggestion
Check it out @ [hack.acmucsd.com](https://hack.acmucsd.com/)
```

2023-09-07 05:53 UTC, nishantbalaji commented on README.md
>  [**Live Demo (https://hack-website-acmucsd.vercel.app/)**](https://hack-website-acmucsd.vercel.app/)
Also move this to the top right under the title

2023-09-07 05:53 UTC, nishantbalaji commented on pages/hack-school/logistics.mdx
normally i would say this should be in its own PR but its fine since its so small

2023-09-07 05:53 UTC, nishantbalaji commented on README.md
> +## Contributing
mention they can also make a pr if they want? idk

2023-09-07 05:53 UTC, nishantbalaji commented on README.md
> +This project was bootstrapped with [Nextra](https://nextra.site).
and deployed on Vercel

2023-09-07 05:59 UTC, nik-dange commented on pages/hack-school/logistics.mdx
thanks :3

2023-09-10 18:12 UTC, nishantbalaji approved these changes
🚢 🌊

2023-09-10 18:12 UTC, nishantbalaji commented on README.md
> +for improvements, feel free to raise an issue on our repository. Make sure to follow the instructions below to set up your local environment for development.
same line for these

2023-09-10 21:09 UTC, nik-dange commented on README.md
> +for improvements, feel free to raise an issue on our repository. Make sure to follow the instructions below to set up your local environment for development.
what does that mean

2023-09-10 21:37 UTC, merged