Homepage team section added icons and fixing render issues
acmucsd/hack-website pull request #26
Opened 2023-09-13 08:01 UTC by AVERGNET

2023-09-13 08:12 UTC, nishantbalaji requested changes
Looks good! Let's hold off on merge until @angela139 's PR #23 is in. In the meantime, could you fix Nikhils photo being smaller than the rest: 
![image](https://github.com/acmucsd/hack-website/assets/44332326/ba4b5f6c-2b7a-4100-be80-5488d3833bc8)

2023-09-13 15:53 UTC, nik-dange commented
Also in light mode, I think the box shadow is pretty apparent. Should we remove it and possibly add padding to the left side of me and right side of you?
<img width="1440" alt="Screenshot 2023-09-13 at 8 51 27 AM" src="https://github.com/acmucsd/hack-website/assets/16010723/3ad158d2-638c-486c-b103-9cc82539e56e">

2023-09-19 07:17 UTC, angela139 requested changes
Overall, I think it's pretty solid! I think main thing is the layout for mobile/tablet devices has to be fixed and remember to pull in the new changes from the main.

2023-09-19 07:17 UTC, angela139 commented on src/components/team-card/style.module.css
> +    display: flex;
Could you try to use display: grid instead? It looks a little squished on smaller devices right now
<img width="529" alt="Screen Shot 2023-09-19 at 12 06 20 AM" src="https://github.com/acmucsd/hack-website/assets/51968178/feac1cbc-897e-4dbf-8eba-e2a2f00bb683">

2023-09-19 07:17 UTC, angela139 commented on src/components/team-card/index.tsx
> +                  <svg width="18" height="14" viewBox="1 0 16 13.5" fill="none">
Could you store the svgs in separate files and add them to the assets folder? You can add them in as img with src="../../../public/assets/email.svg". I think the code would look cleaner that way.

2023-09-19 07:17 UTC, angela139 commented on src/components/team-card/index.tsx
> +              {member.linkedinLink && (
I don't think you need the member.linkedinLink && part since all of us have a linkedin in the teamMembers array.

2023-09-19 07:17 UTC, angela139 commented on src/components/team-card/index.tsx
> +              {member.email && (
Same thing as the linkedin since we all have the emails

2023-09-25 23:24 UTC, angela139 approved these changes
LGTM!

2023-09-29 01:08 UTC, nishantbalaji approved these changes

2023-09-29 04:29 UTC, merged