Homepage about section
acmucsd/hack-website pull request #28
Opened 2023-09-14 05:41 UTC by nik-dange

Holding off on merging until main homepage PR is merged.

How do i make the images look nice 😭 bruh

2023-09-24 20:59 UTC, angela139 requested changes
Overall, the content for the about section looks good to me! I left a few comments/suggestions about the styling. Let me know if you need any help on implementing the changes! Also, remember to pull new changes from the main.

2023-09-24 20:59 UTC, angela139 commented on src/sections/About/style.module.css
> +.main {
Since the content and image wrappers have the same styling, you can just do 
```
.main, .hackschool, .projects { 

}
```

2023-09-24 20:59 UTC, angela139 commented on src/sections/About/style.module.css
> +  border-radius: 50%;
Instead of oval images, we could do rounded corners instead. Maybe 10px for border radius?

2023-09-24 20:59 UTC, angela139 commented on src/sections/About/style.module.css
> +.hackschoolImage img {
Like the content div wrappers, you can just simplify it with commas 
```
.hackschoolImage, .projectImage, .mainImage { 

}
```

2023-09-24 20:59 UTC, angela139 commented on src/sections/About/style.module.css
> +  display: flex;
Instead of flexbox, I think you can just do `margin: auto` to center an image.

2023-09-24 20:59 UTC, angela139 commented on src/sections/About/index.tsx
> +            (link to projects somehow).
You can add the [projects website](https://projects-website.vercel.app/) when it's done

2023-09-24 23:00 UTC, nik-dange commented on src/sections/About/index.tsx
> +          <img src="assets/hackimage.JPG" alt="hi" />
OOPS remnant from when I was trolling around good catch 😄

2023-09-29 18:52 UTC, AVERGNET approved these changes
This looks great love the formatting LGTM, just quick NIT about links

2023-09-29 18:52 UTC, AVERGNET commented on src/sections/About/index.tsx
> +            <a href="https://acmurl.com/apply-hackschool" target="_blank" rel="noopener noreferrer">
NIT: Kind of hard to see those are links, in the textbook chapters the links are orange, makes it easier to see.

2023-10-02 04:41 UTC, angela139 approved these changes
LGTM! I agree with Alexis about making the links more apparent tho. We can probably do a comprehensive review on the styling later on though. I think font sizing for the headers are a little different and there's still a border bottom on the about section. You can remove it for now.

2023-10-02 05:41 UTC, charvishukla commented
hi I just saw this, jaw has dropped, looks great :-)

2023-10-02 06:06 UTC, merged