React Page
acmucsd/hack-website pull request #30
Opened 2023-09-18 04:11 UTC by AVERGNET

2023-09-18 05:05 UTC, nik-dange reviewed
I'll take a closer look a bit later, but from initial observations, is this breaking on your side too?
<img width="381" alt="Screenshot 2023-09-17 at 10 04 24 PM" src="https://github.com/acmucsd/hack-website/assets/16010723/4b7e73ff-00ed-4011-8143-799dbc6bcd2a">

2023-09-19 18:20 UTC, nik-dange requested changes
Overall looks pretty solid! Just a few comments from me

2023-09-19 18:20 UTC, nik-dange commented on pages/hack-school/react.mdx
> +React is a JavaScript library for building user interfaces. It allows you to to create interactive, complex, and dynamic user interfaces by breaking them down into small, isolated pieces of code call
underline and bold "components", it would emphasize it more

2023-09-19 18:20 UTC, nik-dange commented on pages/hack-school/react.mdx
> +In React, components are the fundamental building blocks of user interfaces. They are independant and reusable pieces of UI and can range from small, simple elements like buttons or input fields to e
pieces of the UI

2023-09-19 18:20 UTC, nik-dange commented on pages/hack-school/react.mdx
> +![components nested](pages/hack-school/images/components2.PNG)
If we can, maybe we should have a link for citing/crediting the images that we pull. Great image though, I like it a lot

2023-09-19 18:20 UTC, nik-dange commented on pages/hack-school/react.mdx
> +Props (short for properties) allow you to pass data from a parent component to a child component. They are a way to make your components dynamic and reusable by enabling you to customize a component'
Maybe link to the react documentation on concepts

2023-09-19 18:20 UTC, nik-dange commented on pages/hack-school/react.mdx
> +## Use State
title should be

## useState

2023-09-24 21:31 UTC, angela139 commented on pages/hack-school/react.mdx
> +Some common React Hooks include `useState`, `useEffect`, `useContext`, `useMemo`, `useReducer`, and [more](https://react.dev/reference/react).
It would be nice to have a section with information about useEffect since it's also pretty commonly used in React

2023-09-24 21:52 UTC, angela139 requested changes
Overall, I really like the content and examples! I left some suggestions and pointed out some typos.

2023-09-24 21:52 UTC, angela139 commented on pages/hack-school/react.mdx
> +Some common React Hooks include `useState`, `useEffect`, `useContext`, `useMemo`, `useReducer`, and [more](https://react.dev/reference/react).
It would be nice to have a section with information about useEffect since it's also pretty commonly used in React

2023-09-24 21:52 UTC, angela139 commented on pages/hack-school/react.mdx
> +Each component can hold other components to make more complex sturcutres as show below:
Typo: structures

2023-09-24 21:52 UTC, angela139 commented on pages/hack-school/react.mdx
> +        <Tweet key={tweet.id} tweet={tweet} />
It would be good to mention in a comment that in React you need a unique key for an element when there's a list of elements since it identifies which element is getting modified or deleted.

2023-09-24 21:52 UTC, angela139 commented on pages/hack-school/react.mdx
> +Consider the tweet example above but where we pass in data through props from the partent component which is `Tweets` to the child component `Tweet`:
Typo: parent

2023-09-24 21:52 UTC, angela139 commented on pages/hack-school/react.mdx
> +      <div>
Maybe mention somewhere that you have to wrap all React components in a single root element like a div since React expects its components to return only one element

2023-09-25 16:57 UTC, nik-dange approved these changes
lgtm 🚀

2023-09-25 18:20 UTC, angela139 approved these changes

2023-09-25 23:23 UTC, merged