Adding Images To CSS Page
acmucsd/hack-website pull request #78
Opened 2024-08-07 02:56 UTC by shreyaNagunuri

2024-08-09 08:20 UTC, kevinlu021 commented on pages/hack-school/css.mdx
>  </div>
can we also add a universal selector into the code for styles.css

2024-08-09 08:26 UTC, kevinlu021 commented on pages/hack-school/css.mdx
> +![shadowed_box](pages/hack-school/CSS_images/shadowed_box.png)
i think some of these css properties are excessive, like shadows, transition animations, and list styles. what do you think @angela139

2024-08-13 03:48 UTC, angela139 requested changes
Overall, I think the new images will really help people visual the CSS properties more! I added some comments for areas of improvement

2024-08-13 03:48 UTC, angela139 commented on pages/hack-school/css.mdx
> +![shadowed_box](pages/hack-school/CSS_images/shadowed_box.png)
i think we probably don't need list styles and animation. In the future, I think I will make a page for my advanced css workshops where we can cover things like animations, flex box, grid, etc in more depth.

2024-08-13 03:48 UTC, angela139 commented on pages/hack-school/css.mdx
>  - **Flexbox and Grid**: `display: flex`, `display: grid`, etc. - Utilizing CSS layout systems like Flexbox and Grid to create responsive and flexible layouts (see section below).
Try to add some images for flexbox. Images like this will be helpful for people to grasp the concepts more: 
![image](https://github.com/user-attachments/assets/5e199c7f-b254-4516-8c02-724e5004d47a)

2024-08-13 03:48 UTC, angela139 commented on pages/hack-school/css.mdx
>  - **Margins**: `margin` - Adjusting the space around an element, controlling the gap between elements.
For the section on margin, padding, border, it would be helpful to have an image of the box model so people understand how it all comes together: 
![image](https://github.com/user-attachments/assets/bc88642a-15dd-4e5c-b37f-2efe080d43ef)

2024-08-13 03:48 UTC, angela139 commented on pages/hack-school/CSS_images/floating_image.png
This image looks kinda blurry on the website. I think you should use a higher quality one or adjust width/height to optimize the quality

2024-09-10 04:50 UTC, angela139 approved these changes
LGTM! Just remember to remove the .DS_Store cache files before you merge it in

2024-09-10 04:50 UTC, angela139 commented on pages/hack-school/.DS_Store
Remove .DS_Store file

2024-09-10 04:50 UTC, angela139 commented on pages/hack-school/CSS_images/.DS_Store
Remove .DS_Store file

2024-09-10 06:09 UTC, merged